[package]
name = "scribble"
version = "0.1.0"
authors = ["jli <jli@circularly.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17.1"
rand = "0.7.3"
rand_distr = "0.2.2"
